package rabbitmq.client.routing;

import com.rabbitmq.client.*;
import rabbitmq.client.C;
import rabbitmq.client.RabbitUtil;

import java.io.IOException;

/**
 * spring-engine 2015/12/27 14:00
 * fuquanemail@gmail.com
 */
public class InfoConsumer {
    public static void main(String[] args) throws IOException {

        final String clientName = C.getClient();

        Channel channel = RabbitUtil.getChannel();
        channel.exchangeDeclare("routing-logs", "direct");

        String queueName = channel.queueDeclare().getQueue();
        channel.queueBind(queueName, "routing-logs", "info");
        channel.queueBind(queueName, "routing-logs", "debug");

        Consumer consumer = new DefaultConsumer(channel) {
            @Override
            public void handleDelivery(String consumerTag, Envelope envelope, AMQP.BasicProperties properties, byte[] body)
                    throws IOException {
                String message = new String(body, "UTF-8");
                System.out.println(clientName+ " Received: '" + message + "'");
                try {
                    Thread.sleep(1000);
                } catch (InterruptedException e) {
                    e.printStackTrace();
                }
            }
        };
        //the consumerTag generated by the server
        String consumerTag = channel.basicConsume(queueName, true, consumer);
        System.err.println("consumerTag: "+consumerTag);

    }
}
